### ISSUE TITLE
Move authentication configuration into its own file

### ISSUE THREAD

**Issue by CrazyPyroEagle** [NateNate60/ToS_Helper_Bot#1]
The username, password, and client secret should be moved into a seperate configuration file.
That way, configuration files can easily be uploaded to the repository without accidentally leaking the secrets (see [.gitignore](https://git-scm.com/docs/gitignore)).

Note that the .gitignore won't apply to you if you continue to make changes by manually uploading files, but it will save anyone who uses a Git client to fork/contribute.

**Comment by NateNate60** [comment]
By uncommenting the appropriate lines in config.py, auth.py can be used instead.

Added auth.py to gitignore
